# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/p.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led1_0_0/design_1_led1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led1_0_0 || ORIG_REF_NAME==design_1_led1_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led2_0_0/design_1_led2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led2_0_0 || ORIG_REF_NAME==design_1_led2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_switch_0_0/design_1_switch_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_switch_0_0 || ORIG_REF_NAME==design_1_switch_0_0} -quiet] -quiet

# XDC: c:/Student/PRNE2024/zaj1_18.10.2024/zaj1_18.10.2024.gen/sources_1/bd/design_1/design_1_ooc.xdc
